# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luyentu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('hash_value', models.CharField(max_length=100)),
            ],
        ),
    ]
